<?php
/**
 * Copyright (C) EC Brands Corporation - All Rights Reserved
 * Contact Licensing@ECInternet.com for use guidelines
 */
declare(strict_types=1);
?>

<?php /** @var \Magento\Backend\Block\Template $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<?php /** @var \ECInternet\Analysis\ViewModel\Analysis\Index $viewModel */ ?>
<?php $viewModel = $block->getData('view_model'); ?>

<div class="table-wrapper">
    <table class="table admin__control-table">
        <thead>
        <tr>
            <th scope="col"><?= $escaper->escapeHtml(__('Type')) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Item')) ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Result')) ?></th>
        </tr>
        </thead>
        <tbody>
        <tr class="row">
            <td>Client-Size Optimization</td>
            <td>CSS Minification</td>
            <td><?= $escaper->escapeHtml($viewModel->getCssMinificationResult()) ?></td>
        </tr>
        <tr class="row">
            <td>Client-Size Optimization</td>
            <td>JS Minification</td>
            <td><?= $escaper->escapeHtml($viewModel->getJsMinificationResult()) ?></td>
        </tr>
        <tr class="row">
            <td>Client-Size Optimization</td>
            <td>HTML Minification</td>
            <td><?= $escaper->escapeHtml($viewModel->getHtmlMinificationResult()) ?></td>
        </tr>
        <tr class="row">
            <td>System Setting</td>
            <td>Admin password lifetime (days)</td>
            <td><?= $escaper->escapeHtml($viewModel->getPasswordLifetime()) ?></td>
        </tr>
        <tr class="row">
            <td>System Setting</td>
            <td>Admin forced password update</td>
            <td></td>
        </tr>
        <tr class="row">
            <td>Indexer</td>
            <td>All set to "Reindex on Schedule"</td>
            <td></td>
        </tr>
        </tbody>
    </table>
</div>
